server:
  port: 8083
spring:
  application:
    name: API-GATEWAY 
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**

      - id: HOTELSERVICE
        uri: lb://HOTELSERVICE
        predicates:
        - Path=/hotels/**

      - id: RATINGSERVICE
        uri: lb://RATINGSERVICE
        predicates:
        - Path=/ratings/**

instance:
    prefer-ip-address: true
client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/Eureka
