server:
  port: 8083
spring:
  application:
    name: API-GATEWAY 
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**

      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**

      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oav0el41ysalxu8a697
            client-secret: WOxjdYGKMFVCj5d_oCnPb2tC_fa91SsZpoPS4e1D8wp9X3rYQwRVAj4mtSwBKK12
            scope:
            - openid
            - profile
            - email
            - offline_access
            provider: okta
            client-name: Hotel_Service 
        provider:
          okta:
            issuer-uri: https://integrator-4084965.okta.com/oauth2/default
      resourceserver:
        jwt:
          issuer-uri: https://integrator-4084965.okta.com/oauth2/default
          audiences:
          - api://default

logging:
  level:
    '[org.springframework.security.config.debug]': DEBUG


instance:
    prefer-ip-address: true
client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/Eureka


