server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-4084965.okta.com/oauth2/default
          audiences:
          - api://default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/Eureka
