server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: Shagun@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true