server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Shagun@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  security:
    oauth2:
      client:
        registration:       
          internal-service:
           authorization-grant-type: client_credentials
           client-id: 0oav0el41ysalxu8a697
           client-secret: WOxjdYGKMFVCj5d_oCnPb2tC_fa91SsZpoPS4e1D8wp9X3rYQwRVAj4mtSwBKK12
           provider: okta
           scope:
            - internal
        provider:
          okta:
            issuer-uri: https://integrator-4084965.okta.com/oauth2/default
      resourceserver:
        jwt:
          issuer-uri: https://integrator-4084965.okta.com/oauth2/default
          audiences:
          - api://default
logging:
  level:
     org.springframework.security.oauth2: DEBUG
     org.springframework.web.client.RestTemplate: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/Eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
       configs:
         default:
          registerHealthIndicator : true
          eventConsumerBufferSize : 10
          failureRateThreshold : 50
          minimumNumberOfCalls : 5
          waitDurationInOpenState : 6s
          permittedNumberOfCallsInHalfOpenState : 3
          automaticTransitionFromOpenToHalfOpenEnabled : true
          slidingWindowSize : 10
          slidingWindowType : COUNT_BASED 
       instances:
          ratingHotelBreaker:
            baseConfig: default
          ratingWithHotelBreaker:
            baseConfig: default				