server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice
  application:
    name: RATING-SERVICE
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
      mongodb:
        driver: DEBUG 
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/Eureka

    